networks:
  local:
    driver: ${NETWORKS_DRIVER}

volumes:
  mssql-data:
  mysql-data:
  postgres-data:
  mongo-data:
  redis-data:

services:
  ### MSSQL #################################################
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "${MSSQL_PORT}:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_PASSWORD}
    volumes:
      - mssql-data:/data
    networks:
      - local

  ### MySQL #################################################
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - local

  ### PostgreSQL ############################################
  psql:
    image: postgres:latest
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local
  
  ### Mongo #################################################
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - local

  ### Redis #################################################
  redis:
    image: redis:latestz
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - local
